// SPDX-License-Identifier: GPL-3.0-only
// Generated from TitanSwapper.lua with the Lua 5.4 compiler, stripped of debug data.
// Source SHA256: 80B1D56E2EBF4BC4523021CAF09DB896C7C59CC23A95D19706BA1B4B14023A5B
namespace KM.SV.TitanSwapper;
internal static class SvTitanSwapperBytecode
{
    internal const string Value =
        "G0x1YVQAGZMNChoKBAgIeFYAAAAAAAAAAAAAACh3QAGAgIAAARK8UQAAABMAAABSAAAAiwAAAI4AAQEDAQEAg4EBAMQAAwXLgAAAEIAFBMwAAAHNgAEAtgAA" +
        "AIsAAAUTAQAAUgAAAJMBAQBSAAAAkoEGB8QAAwILAQAFkwEAAFIAAAATAgEAUgAAABKCBgdEAQMCiwEABRMCAABSAAAAkwIBAFIAAACSggYHxAEDAgGC/3+L" +
        "AgAICwMACQ4DBgqLAwALjgMHCgsEAAwOBAgKjgQGDQsFAA4OBQoPjgUHEA4GCBHPBgAAT4cAAM8HAQASAw0Pz4cBAAsIAA7PCAIAEggPEU+IAgASBBEQTwgD" +
        "AJIDEBBGiAEBkgSHc3RyaW5nBIdnbWF0Y2gEkEtNX1RJVEFOX0xBQkVMUwSGW147XSsRBI1zZXRtZXRhdGFibGUEh19fbW9kZQSCawSKYzA1NDI0Q0Y2BJJD" +
        "MkQ3RjQ4NjQyNTQ4Nzc1NQSKcHJvdG90eXBlBJJDQTVBNTYwNjI5OEREQ0IyOQSSQ0IxMkQ5Q0EzOERCN0IyRTEEkkYzNTBDNjJEODg1RDMzQTY0BJJDNkM1" +
        "M0Y1RERGNzRGNTg5NwSSU0MxMDI0NjExODA3MUNDMjYEkkY2NjcyQ0YzNzg1N0Y1QkUxBJJGM0NDOTkwREE2QzZBN0M0QYEBAACHgJKaAQADnI4AAADCAAAA" +
        "uAEAgBKAAAGLAAACTwEAAMQAAgGOAAADwgAAADgIAICOAAADjQABDMIAAAA4BgCAjgAABMIAAAC4BACAjgAAA40AAQyNAAEADgEABLkAAgC4AQCAjgAAA40A" +
        "AQwOAQAFkQAAAsaAAQCGBIdoaWRkZW4BBIZwY2FsbASGc2V0dXAEhmFjdG9yBIZzdG9yeYEAAACBgJWVAAADhQsAAAAUgAABCwEAAkQAAwFHAAEAgwSGbW9k" +
        "ZWwEimY2NzU0NDUzRQSIdmlzaWJsZYEBAACAgICAgICAgICAnKUBAAWUiQAAAAABAADEAAIBjgAAAMIAAAC4AgCAjgAAABKAAAELAQECiwECAwACAQBEAQMB" +
        "jgAABMIAAAA4AQCADgEABIkAAwCQgAIBEoAEAccAAQCFBIVuYW1lAASGcGNhbGwEimZBRTFEMjI4RQSGYWN0b3KEAQ0AAAAAAQUAAQMAgICAgICAp68FAA6s" +
        "iQIAAAADAACAAwEAAAQCAIAEAwAABQQAxAIGAT0BgAC4AQCAiQIBAIwCBQHCggAAOAAAgMcCAQCNAgAFjQIFARMDAwBSAAAAEgMABRIDAQESAwIAjQMABQsE" +
        "AgMOBAgERAQBApEDAQiLAwIFCQQAAIAEAAADBQMAgAUBADUFAgCABQIAAAYDAIAGBADEAwcCwgMAADgBAIAJBAMAEAQABrgAAIANBAAFEQQBBUcEAQCHBIlm" +
        "YWxsYmFjawSGbGFiZWwEhnNldHVwBIpjMDNDODAzMEUEimYxMDFEODExRgSGcGNhbGwEimttX3RpdGFuX4QBCQABAAAAAAABAQCAgICAgICx0wEAEQGZjgAA" +
        "AA0BAQwNAQIAEgABAg4BAAFCAQAAOAIAgA4BAAEUgQICRAECAkKBAAC4AACABQEAAEgBAgAOAQABFIECA0QBAgJCAQAAuAEAgJSBAgLEAQICwoEAALgAAICF" +
        "AQAAyAECAIsBAASOAQMFAwIDAMQBAgLCAQAAuAEAgBSCAwJEAgICQoIAALgAAIAFAgAASAICAAsCAAgOAgQJjgIAAUQCAgISAAcECwIACA4CBAqOAgAHCAMA" +
        "AEQCAwJCggAAuAAAgAUCAABIAgIADgIABxSCBAxEAgICEgALBA0CAQUNAgQBFIIEDQGD/39EAgMCjgIAAZSCBQ7EAgIECQQBABUECIAvBIAGCgQBAAMECACL" +
        "BAARCQUBAMQEAgI1BAIAEgAPCAsEAhKABAMADgUAD4AFBAABhv9/gAYFAAAHBgCABwcARAQIAQEEAICBhCuBAQUAgEqEHwAOBgABFIYMAkQGAgJCBgAAuAMA" +
        "gBSGAgJEBgICQgYAALgBAIAUhgMCRAYCAkKGAAC4AACABQYAAEgGAgALBgITjgYAD0QGAgJCBgAAuBMAgAsGAhSOBgAPRAYCAkIGAAA4EQCAlIYMAsQGAgLC" +
        "BgAAOA8AgJSGDAPEBgIClIYNAsQGAgLCBgAAOAwAgBIAFQyLBgAWjgYNF44GDRgUhwwZRAcCAowGDQ7CBgAAOAIAgA4HDRpCBwAAuAAAgBSHDRpEBwIBEoAb" +
        "HA4HAAcUhw4dBQgAAEQHAwENBwEMEQcADAkHAwAQBwwABwcAAEgHAgALBgAeDgYMH0QGAQFJBCAABQQAAEgEAgBHBAEAoASGc2V0dXAEhnN0b3J5BIpmOUQ4" +
        "QkMxNzgEimY0NjJDOUI3MASKYzY4MkQ4RTRGBIpmRUY5NEQxMUQEh2JhdHRsZQSGbW9kZWwEimNFQ0I5MUUzMQSKZkI0MUZEMjJGBIpmMDRBQ0MzRjIEiHZp" +
        "c2libGUEimYyQ0I4NzU4RgSKZkZEMDM0QkMzBIpmNzM2MEVEMDMEhW5hbWUEkWttX3RpdGFuX2NvbWJhdF8EiXRvc3RyaW5nBIpmM0REN0IyMUYEimY3ODkz" +
        "MzI4RQSKZjZGNDFCNjA4BIZhY3RvcgSSQzNCMDkxNzc3RTNFQzk0QTUEklMzQUIyN0ZGQUYzM0VGRDJEBIJoBIpmQjNDRjFERUIEkkY5N0I3QTAyRkQzNDAx" +
        "QUNEBIdoaWRkZW4RBIpmNjc1NDQ1M0UEkkNDNkZFODI4MTlDNkUxRDU1BJJTMTJGNjNFRTQ3RkZDQjE4M4QAAAABBAABBQABAwCAgICAgIDV7AEACbyJAAAA" +
        "jAABAMKAAAC4AQCACQEBAIABAABFgQIARoEAAAkBAAAQgQAABQEAAIsBAgETAgAAUgAAAJMCAQBSAAAATwMAAJICAgbEAQMCtwEAAAUCAACFAgAADQMAAT0D" +
        "gwC4AgCACwMCA4kDBAAABAEARAMDA4ACBwAAAgYAQgIAALgAAIDCggAAuAQAgAkDAwCAAwEARAMCAQ0DAAWOAwEEEQMBBwkDAQCAAwAARAMCAEaDAAAJAwEA" +
        "gAMAAEQDAgJCgwAAOAIAgI0DAAUOBAEEkQMBCIgDAADGgwIAiQMFAJADBgEHAQAARoMCAMaDAQCFAASNc2V0bWV0YXRhYmxlBIhfX2Nsb3NlBIZwY2FsbASJ" +
        "ZmFsbGJhY2uGAQEAAQoAAAAAAQ4AAQ8AAQIAgYDa3wAAAosJAAAAQoAAADgDAIAJAAEAiQACAEQAAgEJAAMADQAABYsAAgARAAEBRwABAIEEiWZhbGxiYWNr" +
        "hAECAAADAAEBAAEAAICAgICAgICAgIDu9QEABZeNAAACwgAAADgBAIANAQACiQAAAIwAAQLCgAAAuAEAgAkBAQCAAQAARQECAEYBAAAUgQAABQIAAEQBAwEJ" +
        "AQEAgAEAAEQBAgEJAQIAgAEBAEQBAgERgAIBRwEBAIIEkkY5RTA5QTIwNEU2MjlGOUYzAIMBAwABDAABDgCAgICAgID3/wEABpaJAAAAjAABAMKAAAC4AQCA" +
        "CQEBAIABAABFgQIARoEAAAsBAgCTAQAAUgAAABMCAQBSAAAAzwIAABICAQVEAQMCNwEAAIkBAQAAAgAAxAECAMaBAADGgQEAggSNc2V0bWV0YXRhYmxlBIhf" +
        "X2Nsb3NlhAECAAELAAAAAAEOAIGA+v0AAAKHCQAAAIkAAQBEAAIBiQADAAkAAgAQgAEARwABAIEAhAADAAEBAAAAAAEAAICAgICAgICAgICAgIA=";
}
