// SPDX-License-Identifier: GPL-3.0-only

namespace KM.Formats.ZA.Generated.FashionCatalog;

table ZaDressUpCatalogEntry {
    ItemId:uint;
    ModelPart:string (required);
    CatalogGroupCode:uint;
    ModelVariant:string (required);
    CategoryCode:uint;
    ColorVariantCode:uint;
    PrimaryColorLabel:string (required);
    SecondaryColorLabel:string (required);
    ReservedFlagA:bool;
    Price:uint;
    UiIndex:uint;
    FootwearSubtype:string;
    ReservedFlagB:bool;
}

table ZaDressUpCatalogArray {
    Entries:[ZaDressUpCatalogEntry] (required);
}

root_type ZaDressUpCatalogArray;
