// SPDX-License-Identifier: GPL-3.0-only

#include "km_za_202.hpp"
#include "km_settings.hpp"

extern "C" uintptr_t km_za_202_main_base = 0;

namespace {

using km::GuestFilesystemApi;
using km::MemoryCompare;
using km::MemoryCopy;
using km::MemorySet;
using km::ModuleRange;
using km::SettingsFamily;
using km::SettingsState;
using km::SettingsValues;

constexpr uint64_t TitleId = 0x0100F43008C44000ULL;
constexpr uint32_t ProgramIdInfoType = 18;
constexpr uint64_t RequiredPresence = km::PresenceExperienceShare
    | km::PresenceExperienceRate | km::PresenceLevelCap;
constexpr size_t ExpectedTextSize = 0x03164000;
constexpr size_t ExpectedRoOffset = 0x03164000;
constexpr size_t ExpectedDataOffset = 0x03BC2000;
constexpr uint32_t NopInstruction = 0xD503201F;
constexpr uint32_t FarLoadX17 = 0x58000051;
constexpr uint32_t FarBranchX17 = 0xD61F0220;

constexpr uintptr_t ShareCallAOffset = 0x009A3FF4;
constexpr uintptr_t ShareCallBOffset = 0x00D735C0;
constexpr uintptr_t RateSiteAOffset = 0x009A4174;
constexpr uintptr_t RateSiteBOffset = 0x00D73744;
constexpr uintptr_t AwardBuilderOffset = 0x009A4A70;
constexpr uintptr_t MinimumTotalExperienceOffset = 0x00CECB8C;
constexpr uintptr_t SpeciesGetterOffset = 0x00E49940;
constexpr uintptr_t FormGetterOffset = 0x00E4D190;
constexpr uintptr_t CurrentTotalExperienceOffset = 0x00E49F60;
constexpr uintptr_t AppendOffset = 0x03163F70;
constexpr size_t AppendLength = 0x90;

constexpr uintptr_t ResetOffset = 0x02C7F73C;
constexpr uintptr_t RowCountOffset = 0x02C7F778;
constexpr uintptr_t GetRowOffset = 0x02C80230;
constexpr uintptr_t StepRightOffset = 0x02C8063C;
constexpr uintptr_t ApplyRowOffset = 0x02C806DC;
constexpr uintptr_t RefreshRowOffset = 0x02C80708;
constexpr uintptr_t StepLeftOffset = 0x02C80884;
constexpr uintptr_t BackOffset = 0x02C8219C;
constexpr uintptr_t RenderRowOffset = 0x02C83760;
constexpr uintptr_t RenderDescriptionOffset = 0x02C83A94;

constexpr uintptr_t ResetModelOffset = 0x02C7F58C;
constexpr uintptr_t GetRuntimeContextOffset = 0x02C7F694;
constexpr uintptr_t ResetRuntimeContextOffset = 0x0291D724;
constexpr uintptr_t ApplyCategory0Offset = 0x02C7F78C;
constexpr uintptr_t ApplyCategory1Offset = 0x02C7F864;
constexpr uintptr_t ApplyCategory2Offset = 0x02C7F910;
constexpr uintptr_t RenderCategory0Offset = 0x02C83798;
constexpr uintptr_t RenderCategory1Offset = 0x02C83900;
constexpr uintptr_t RenderCategory2Offset = 0x02C839FC;
constexpr uintptr_t DescribeCategory0Offset = 0x02C83AC4;
constexpr uintptr_t DescribeCategory1Offset = 0x02C83B84;
constexpr uintptr_t DescribeCategory2Offset = 0x02C83C44;
constexpr uintptr_t SetRowTitleOffset = 0x02C83D04;
constexpr uintptr_t SetToggleLabelsOffset = 0x02C83DA4;
constexpr uintptr_t SetSliderValueOffset = 0x02C840BC;
constexpr uintptr_t SetDescriptionOffset = 0x02C84210;
constexpr uintptr_t SetMessageTextOffset = 0x002BCBE0;
constexpr uintptr_t StockRuntimeBarrierPointerOffset = 0x03EC32B8;

constexpr uint32_t ShareCallAVanilla = 0x9400029F;
constexpr uint32_t ShareCallBVanilla = 0x97F0C52C;
constexpr uint32_t ShareCallAHook = 0x949EFFDF;
constexpr uint32_t ShareCallBHook = 0x948FC26C;

constexpr uint32_t RateSiteVanilla[] = {
    0xB9401AA8, 0x0B170108, 0xB9001AA8,
};

// Exact unreachable append generated by
// ZaStaticGameplaySettingsMainPatcher.BuildRuntimeManaged for Z-A 2.0.2.
constexpr uint32_t AppendSentinel[] = {
    0xA9BF0BFE, 0x976102BF, 0xA8C10BFE, 0x7100005F,
    0x1A8003E0, 0xD65F03C0, 0xA9BE5BFE, 0xD503201F,
    0xD503201F, 0xD503201F, 0xD503201F, 0xD503201F,
    0xAA1003F6, 0xF9403A60, 0x97739666, 0xB90013E0,
    0xF9403A60, 0x9773A477, 0x2A0003E1, 0xB94013E0,
    0x52800C82, 0x976E22F2, 0x51000408, 0xB90013E8,
    0xF9403A60, 0x977397E3, 0xB94013E8, 0x6B000108,
    0x1A9F8108, 0xB9401AA9, 0x8B0902D6, 0xEB0802DF,
    0x1A8892C8, 0xB9001AA8, 0xA8C25BFE, 0xD65F03C0,
};
static_assert(sizeof(AppendSentinel) == AppendLength);

#define KM_ZA_PREIMAGE(name, ...) \
    constexpr uint32_t name[] = {__VA_ARGS__}

KM_ZA_PREIMAGE(ResetPreimage,
    0xA9BE7BFD, 0xF9000BF3, 0x910003FD, 0x90009228);
KM_ZA_PREIMAGE(RowCountPreimage,
    0xB940B808, 0x71000D1F, 0x52800068, 0x1A9F3100);
KM_ZA_PREIMAGE(GetRowPreimage,
    0xA9BF7BFD, 0x910003FD, 0xF9408C08, 0xB940B909);
KM_ZA_PREIMAGE(StepRightPreimage,
    0xA9BC7BFD, 0xF9000BF7, 0xA90257F6, 0xA9034FF4);
KM_ZA_PREIMAGE(ApplyRowPreimage,
    0xF9408C00, 0xB940B808, 0x7100091F, 0x540000A0);
KM_ZA_PREIMAGE(RefreshRowPreimage,
    0xD10143FF, 0xA9027BFD, 0xA90357F6, 0xA9044FF4);
KM_ZA_PREIMAGE(StepLeftPreimage,
    0xA9BD7BFD, 0xA90157F6, 0xA9024FF4, 0x910003FD);
KM_ZA_PREIMAGE(BackPreimage,
    0xD101C3FF, 0xA9057BFD, 0xA9064FF4, 0x910143FD);
KM_ZA_PREIMAGE(RenderRowPreimage,
    0x7100085F, 0x540000C0, 0x7100045F, 0x540000E0);
KM_ZA_PREIMAGE(RenderDescriptionPreimage,
    0x7100083F, 0x540000C0, 0x7100043F, 0x540000C0);

KM_ZA_PREIMAGE(ResetModelPreimage,
    0xFC1D0FE8, 0xA900FBFD, 0xF9000FF5, 0xA9024FF4);
KM_ZA_PREIMAGE(GetRuntimeContextPreimage,
    0xA9BD7BFD, 0xA90157F6, 0xA9024FF4, 0x910003FD);
KM_ZA_PREIMAGE(ResetRuntimeContextPreimage,
    0xF9402008, 0xD28A9E49, 0xF2A002A9, 0xB3405128);
KM_ZA_PREIMAGE(ApplyCategory0Preimage,
    0xA9BD7BFD, 0xF9000BF5, 0xA9024FF4, 0x910003FD);
KM_ZA_PREIMAGE(ApplyCategory1Preimage,
    0xA9BE7BFD, 0xA9014FF4, 0x910003FD, 0x71000C3F);
KM_ZA_PREIMAGE(ApplyCategory2Preimage,
    0xA9BD7BFD, 0xF9000BF5, 0xA9024FF4, 0x910003FD);
KM_ZA_PREIMAGE(RenderCategory0Preimage,
    0xD10203FF, 0xA9067BFD, 0xA9074FF4, 0x910183FD);
KM_ZA_PREIMAGE(RenderCategory1Preimage,
    0xD101C3FF, 0xA9047BFD, 0xF9002BF5, 0xA9064FF4);
KM_ZA_PREIMAGE(RenderCategory2Preimage,
    0xD10143FF, 0xA9027BFD, 0xF9001BF5, 0xA9044FF4);
KM_ZA_PREIMAGE(DescribeCategory0Preimage,
    0xD100C3FF, 0xA9027BFD, 0x910083FD, 0xD284C8A8);
KM_ZA_PREIMAGE(DescribeCategory1Preimage,
    0xD100C3FF, 0xA9027BFD, 0x910083FD, 0xD284C8A8);
KM_ZA_PREIMAGE(DescribeCategory2Preimage,
    0xD100C3FF, 0xA9027BFD, 0x910083FD, 0xD284C8A8);
KM_ZA_PREIMAGE(SetRowTitlePreimage,
    0xD102C3FF, 0xA9097BFD, 0xA90A4FF4, 0x910243FD);
KM_ZA_PREIMAGE(SetToggleLabelsPreimage,
    0xD104C3FF, 0xA90E7BFD, 0xA90F67FC, 0xA9105FF8);
KM_ZA_PREIMAGE(SetSliderValuePreimage,
    0xD10383FF, 0xA90B7BFD, 0xF90063F5, 0xA90D4FF4);
KM_ZA_PREIMAGE(SetDescriptionPreimage,
    0xD10183FF, 0xA9047BFD, 0xA9054FF4, 0x910103FD);
KM_ZA_PREIMAGE(SetMessageTextPreimage,
    0xD10103FF, 0xA9017BFD, 0xF90013F5, 0xA9034FF4);
KM_ZA_PREIMAGE(AwardBuilderPreimage,
    0xD10243FF, 0xFD0023E8, 0xF9002FF9, 0xA904FBFD);
KM_ZA_PREIMAGE(SpeciesGetterPreimage,
    0xA9BC7BFD, 0xF9000BF7, 0xA90257F6, 0xA9034FF4);
KM_ZA_PREIMAGE(FormGetterPreimage,
    0xA9BC7BFD, 0xF9000BF7, 0xA90257F6, 0xA9034FF4);
KM_ZA_PREIMAGE(CurrentExperiencePreimage,
    0xA9BC7BFD, 0xF9000BF7, 0xA90257F6, 0xA9034FF4);
KM_ZA_PREIMAGE(MinimumExperiencePreimage,
    0xD100C3FF, 0xA9017BFD, 0xF90013F3, 0x910043FD);

#undef KM_ZA_PREIMAGE

struct FarBranch {
    uint32_t load_target;
    uint32_t branch_target;
    uintptr_t target;
};
static_assert(sizeof(FarBranch) == 0x10);

struct MessageKey {
    uint64_t hash;
    const char* name;
    uint64_t length;
};
static_assert(sizeof(MessageKey) == 0x18);

constexpr uint64_t FnvOffsetBasis = 0xCBF29CE484222645ULL;
constexpr uint64_t FnvPrime = 0x100000001B3ULL;

constexpr uint64_t HashMessageKey(const char* value, size_t length) {
    auto hash = FnvOffsetBasis;
    for (size_t index = 0; index < length; ++index) {
        hash ^= static_cast<uint8_t>(value[index]);
        hash *= FnvPrime;
    }
    return hash;
}

template <size_t Length>
constexpr MessageKey MakeMessageKey(const char (&value)[Length]) {
    static_assert(Length > 1);
    return MessageKey{HashMessageKey(value, Length - 1), value, Length - 1};
}

constexpr char ExperienceShareName[] = "km_exp_share";
constexpr char ExperienceShareDescription[] = "km_exp_share_desc";
constexpr char ExperienceRateName[] = "km_exp_rate";
constexpr char ExperienceRateDescription[] = "km_exp_rate_desc";
constexpr char LevelCapName[] = "km_level_cap";
constexpr char LevelCapDescription[] = "km_level_cap_desc";
constexpr char ExperienceRateValuePrefix[] = "km_exp_rate_value_";
constexpr char LevelCapValuePrefix[] = "km_level_cap_value_";
constexpr char LevelCapOffName[] = "km_level_cap_value_off";
constexpr char EnabledName[] = "km_enabled";
constexpr char DisabledName[] = "km_disabled";

constexpr auto ExperienceShareNameKey = MakeMessageKey(ExperienceShareName);
constexpr auto ExperienceShareDescriptionKey = MakeMessageKey(ExperienceShareDescription);
constexpr auto ExperienceRateNameKey = MakeMessageKey(ExperienceRateName);
constexpr auto ExperienceRateDescriptionKey = MakeMessageKey(ExperienceRateDescription);
constexpr auto LevelCapNameKey = MakeMessageKey(LevelCapName);
constexpr auto LevelCapDescriptionKey = MakeMessageKey(LevelCapDescription);
constexpr auto LevelCapOffKey = MakeMessageKey(LevelCapOffName);
constexpr auto EnabledKey = MakeMessageKey(EnabledName);
constexpr auto DisabledKey = MakeMessageKey(DisabledName);

constexpr size_t ValueMessageKeyCapacity = 32;
char g_experience_rate_value_names[51][ValueMessageKeyCapacity]{};
MessageKey g_experience_rate_value_keys[51]{};
char g_level_cap_value_names[100][ValueMessageKeyCapacity]{};
MessageKey g_level_cap_value_keys[100]{};

constexpr char JournalPath[] =
    "sd:/config/km-editor/gameplay-settings/0100F43008C44000/settings.bin";

enum ActivationState : uint32_t {
    ActivationIdle = 0,
    ActivationRetrying = 1,
    ActivationActive = 2,
    ActivationRejected = 3,
};

GuestFilesystemApi g_filesystem{};
ModuleRange g_main{};
SettingsState g_persisted{};
SettingsValues g_draft = km::VanillaSettings;
volatile uint64_t g_effective_snapshot;
volatile uint32_t g_activation_state;
volatile uint32_t g_menu_lock;
volatile uint32_t g_journal_ready;
volatile uint32_t g_journal_worker_state;
bool g_dirty;
alignas(0x1000) uint8_t g_retry_stack[0x4000];

template <typename Function>
Function MainFunction(uintptr_t offset) {
    return reinterpret_cast<Function>(km_za_202_main_base + offset);
}

bool IsInsideText(const ModuleRange& module, uintptr_t offset, size_t length) {
    return module.base != 0 && offset <= module.text_size
        && length <= module.text_size - offset;
}

bool Matches(const ModuleRange& module, uintptr_t offset,
             const void* expected, size_t length) {
    return expected != nullptr && IsInsideText(module, offset, length)
        && MemoryCompare(reinterpret_cast<const void*>(module.base + offset),
                         expected, length) == 0;
}

template <size_t Count>
bool MatchesWords(const ModuleRange& module, uintptr_t offset,
                  const uint32_t (&expected)[Count]) {
    return Matches(module, offset, expected, sizeof(expected));
}

// Scalar form used for single instruction preimages.
bool MatchesWord(const ModuleRange& module, uintptr_t offset, uint32_t expected) {
    return Matches(module, offset, &expected, sizeof(expected));
}

bool MatchesExactProfile(const ModuleRange& module) {
    if (module.text_size != ExpectedTextSize
        || module.ro_base != module.base + ExpectedRoOffset
        || module.data_base != module.base + ExpectedDataOffset
        || !MatchesWord(module, ShareCallAOffset, ShareCallAVanilla)
        || !MatchesWord(module, ShareCallBOffset, ShareCallBVanilla)
        || !MatchesWords(module, RateSiteAOffset, RateSiteVanilla)
        || !MatchesWords(module, RateSiteBOffset, RateSiteVanilla)
        || !MatchesWords(module, AppendOffset, AppendSentinel)
        || !MatchesWords(module, ResetOffset, ResetPreimage)
        || !MatchesWords(module, RowCountOffset, RowCountPreimage)
        || !MatchesWords(module, GetRowOffset, GetRowPreimage)
        || !MatchesWords(module, StepRightOffset, StepRightPreimage)
        || !MatchesWords(module, ApplyRowOffset, ApplyRowPreimage)
        || !MatchesWords(module, RefreshRowOffset, RefreshRowPreimage)
        || !MatchesWords(module, StepLeftOffset, StepLeftPreimage)
        || !MatchesWords(module, BackOffset, BackPreimage)
        || !MatchesWords(module, RenderRowOffset, RenderRowPreimage)
        || !MatchesWords(module, RenderDescriptionOffset, RenderDescriptionPreimage)
        || !MatchesWords(module, ResetModelOffset, ResetModelPreimage)
        || !MatchesWords(module, GetRuntimeContextOffset, GetRuntimeContextPreimage)
        || !MatchesWords(module, ResetRuntimeContextOffset, ResetRuntimeContextPreimage)
        || !MatchesWords(module, ApplyCategory0Offset, ApplyCategory0Preimage)
        || !MatchesWords(module, ApplyCategory1Offset, ApplyCategory1Preimage)
        || !MatchesWords(module, ApplyCategory2Offset, ApplyCategory2Preimage)
        || !MatchesWords(module, RenderCategory0Offset, RenderCategory0Preimage)
        || !MatchesWords(module, RenderCategory1Offset, RenderCategory1Preimage)
        || !MatchesWords(module, RenderCategory2Offset, RenderCategory2Preimage)
        || !MatchesWords(module, DescribeCategory0Offset, DescribeCategory0Preimage)
        || !MatchesWords(module, DescribeCategory1Offset, DescribeCategory1Preimage)
        || !MatchesWords(module, DescribeCategory2Offset, DescribeCategory2Preimage)
        || !MatchesWords(module, SetRowTitleOffset, SetRowTitlePreimage)
        || !MatchesWords(module, SetToggleLabelsOffset, SetToggleLabelsPreimage)
        || !MatchesWords(module, SetSliderValueOffset, SetSliderValuePreimage)
        || !MatchesWords(module, SetDescriptionOffset, SetDescriptionPreimage)
        || !MatchesWords(module, SetMessageTextOffset, SetMessageTextPreimage)
        || !MatchesWords(module, AwardBuilderOffset, AwardBuilderPreimage)
        || !MatchesWords(module, SpeciesGetterOffset, SpeciesGetterPreimage)
        || !MatchesWords(module, FormGetterOffset, FormGetterPreimage)
        || !MatchesWords(module, CurrentTotalExperienceOffset, CurrentExperiencePreimage)
        || !MatchesWords(module, MinimumTotalExperienceOffset, MinimumExperiencePreimage)) {
        return false;
    }
    return true;
}

const ModuleRange* FindExactMain(const ModuleRange* modules, size_t module_count) {
    const ModuleRange* match = nullptr;
    for (size_t index = 0; index < module_count; ++index) {
        if (!MatchesExactProfile(modules[index])) {
            continue;
        }
        if (match != nullptr) {
            return nullptr;
        }
        match = &modules[index];
    }
    return match;
}

bool ValuesEqual(const SettingsValues& left, const SettingsValues& right) {
    return left.experience_share == right.experience_share
        && left.experience_rate_basis_points == right.experience_rate_basis_points
        && left.level_cap_enabled == right.level_cap_enabled
        && left.level_cap == right.level_cap;
}

bool IsNativeRepresentable(const SettingsState& state) {
    const auto& values = state.values;
    return (state.presence & RequiredPresence) == RequiredPresence
        && values.experience_rate_basis_points <= 50000
        && values.experience_rate_basis_points % 1000 == 0
        && ((!values.level_cap_enabled && values.level_cap == 100)
            || (values.level_cap_enabled && values.level_cap >= 1
                && values.level_cap <= 100));
}

uint64_t PackValues(const SettingsValues& values) {
    const SettingsState state{
        SettingsFamily::LegendsZA,
        TitleId,
        0,
        RequiredPresence,
        values,
        0,
        true,
    };
    return km::PackSettingsSnapshot(state);
}

bool IsActive() {
    return __atomic_load_n(&g_activation_state, __ATOMIC_ACQUIRE)
        == ActivationActive;
}

bool IsJournalReady() {
    return __atomic_load_n(&g_journal_ready, __ATOMIC_ACQUIRE) != 0;
}

bool TryAcquireMenuLock() {
    uint32_t expected = 0;
    return __atomic_compare_exchange_n(
        &g_menu_lock, &expected, 1, false, __ATOMIC_ACQUIRE, __ATOMIC_RELAXED);
}

void ReleaseMenuLock() {
    __atomic_store_n(&g_menu_lock, 0, __ATOMIC_RELEASE);
}

void AcquireMenuLock() {
    while (!TryAcquireMenuLock()) {
        km_za_202_sleep_thread(0);
    }
}

template <size_t PrefixLength>
bool BuildIndexedMessageKey(
    const char (&prefix)[PrefixLength],
    uint32_t value,
    char* storage,
    size_t capacity,
    MessageKey* output) {
    static_assert(PrefixLength > 1);
    if (storage == nullptr || output == nullptr || capacity < PrefixLength) {
        return false;
    }
    const auto prefix_length = PrefixLength - 1;
    MemoryCopy(storage, prefix, prefix_length);

    char reversed[10]{};
    size_t digit_count = 0;
    do {
        reversed[digit_count++] = static_cast<char>('0' + value % 10U);
        value /= 10U;
    } while (value != 0 && digit_count < sizeof(reversed));
    if (value != 0 || prefix_length + digit_count >= capacity) {
        return false;
    }
    for (size_t index = 0; index < digit_count; ++index) {
        storage[prefix_length + index] = reversed[digit_count - index - 1];
    }
    const auto length = prefix_length + digit_count;
    storage[length] = '\0';
    *output = MessageKey{HashMessageKey(storage, length), storage, length};
    return true;
}

bool PrepareValueMessageKeys() {
    for (uint32_t value = 0; value <= 50; ++value) {
        if (!BuildIndexedMessageKey(
                ExperienceRateValuePrefix,
                value,
                g_experience_rate_value_names[value],
                ValueMessageKeyCapacity,
                &g_experience_rate_value_keys[value])) {
            return false;
        }
    }
    for (uint32_t level = 1; level <= 100; ++level) {
        if (!BuildIndexedMessageKey(
                LevelCapValuePrefix,
                level,
                g_level_cap_value_names[level - 1],
                ValueMessageKeyCapacity,
                &g_level_cap_value_keys[level - 1])) {
            return false;
        }
    }
    return true;
}

uint32_t EncodeBranchLink(uintptr_t source, uintptr_t target) {
    const auto delta = static_cast<int64_t>(target) - static_cast<int64_t>(source);
    if ((delta & 3) != 0 || delta < -(int64_t{1} << 27)
        || delta >= (int64_t{1} << 27)) {
        return 0;
    }
    return 0x94000000U
        | (static_cast<uint32_t>(delta / 4) & 0x03FFFFFFU);
}

FarBranch MakeFarBranch(const void* target) {
    return FarBranch{FarLoadX17, FarBranchX17,
                     reinterpret_cast<uintptr_t>(target)};
}

void BuildRuntimeAppend(uint8_t* output) {
    MemorySet(output, 0, AppendLength);
    for (size_t offset = 0; offset < AppendLength; offset += sizeof(uint32_t)) {
        MemoryCopy(output + offset, &NopInstruction, sizeof(NopInstruction));
    }
    const auto share = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_share_callback));
    const auto rate = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_rate_bridge));
    MemoryCopy(output, &share, sizeof(share));
    MemoryCopy(output + 0x18, &rate, sizeof(rate));
}

bool InstallRuntime(const SettingsState& loaded, bool journal_ready) {
    if (!IsNativeRepresentable(loaded)) {
        return false;
    }

    alignas(8) uint8_t append[AppendLength]{};
    BuildRuntimeAppend(append);
    const uint32_t rate_a[] = {
        NopInstruction,
        NopInstruction,
        EncodeBranchLink(RateSiteAOffset + 8, AppendOffset + 0x18),
    };
    const uint32_t rate_b[] = {
        NopInstruction,
        NopInstruction,
        EncodeBranchLink(RateSiteBOffset + 8, AppendOffset + 0x18),
    };
    if (rate_a[2] == 0 || rate_b[2] == 0) {
        return false;
    }

    const auto reset = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_reset));
    const auto count = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_row_count));
    const auto get = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_get_row));
    const auto step_right = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_step_right));
    const auto apply = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_apply_row));
    const auto step_left = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_step_left));
    const auto back = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_back));
    const auto render = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_render_row));
    const auto describe = MakeFarBranch(
        reinterpret_cast<const void*>(&km_za_202_render_description));

    g_persisted = loaded;
    g_draft = loaded.values;
    g_dirty = false;
    __atomic_store_n(&g_effective_snapshot, PackValues(loaded.values), __ATOMIC_RELEASE);
    __atomic_store_n(
        &g_journal_ready, journal_ready ? 1U : 0U, __ATOMIC_RELEASE);

    const km::ExecutablePatch patches[] = {
        {g_main.base + AppendOffset, AppendSentinel, append, sizeof(append)},
        {g_main.base + ShareCallAOffset, &ShareCallAVanilla,
         &ShareCallAHook, sizeof(ShareCallAHook)},
        {g_main.base + ShareCallBOffset, &ShareCallBVanilla,
         &ShareCallBHook, sizeof(ShareCallBHook)},
        {g_main.base + RateSiteAOffset, RateSiteVanilla,
         rate_a, sizeof(rate_a)},
        {g_main.base + RateSiteBOffset, RateSiteVanilla,
         rate_b, sizeof(rate_b)},
        {g_main.base + ResetOffset, ResetPreimage, &reset, sizeof(reset)},
        {g_main.base + RowCountOffset, RowCountPreimage, &count, sizeof(count)},
        {g_main.base + GetRowOffset, GetRowPreimage, &get, sizeof(get)},
        {g_main.base + StepRightOffset, StepRightPreimage,
         &step_right, sizeof(step_right)},
        {g_main.base + ApplyRowOffset, ApplyRowPreimage, &apply, sizeof(apply)},
        {g_main.base + StepLeftOffset, StepLeftPreimage,
         &step_left, sizeof(step_left)},
        {g_main.base + BackOffset, BackPreimage, &back, sizeof(back)},
        {g_main.base + RenderRowOffset, RenderRowPreimage, &render, sizeof(render)},
        {g_main.base + RenderDescriptionOffset, RenderDescriptionPreimage,
         &describe, sizeof(describe)},
    };
    if (!km::PatchExecutableTransaction(
            patches, sizeof(patches) / sizeof(patches[0]))) {
        __atomic_store_n(&g_effective_snapshot, 0, __ATOMIC_RELEASE);
        return false;
    }
    __atomic_store_n(&g_activation_state, ActivationActive, __ATOMIC_RELEASE);
    return true;
}

bool AdoptLoadedSettings(const SettingsState& loaded) {
    if (!IsNativeRepresentable(loaded) || !TryAcquireMenuLock()) {
        return false;
    }

    g_persisted = loaded;
    if (!g_dirty) {
        g_draft = loaded.values;
        __atomic_store_n(
            &g_effective_snapshot, PackValues(loaded.values), __ATOMIC_RELEASE);
    } else {
        g_dirty = !ValuesEqual(g_draft, loaded.values);
    }
    __atomic_store_n(&g_journal_ready, 1, __ATOMIC_RELEASE);
    ReleaseMenuLock();
    return true;
}

void RetryJournal(void*) {
    for (;;) {
        SettingsState loaded{};
        if (km::LoadSettingsJournal(
                g_filesystem,
                JournalPath,
                SettingsFamily::LegendsZA,
                TitleId,
                RequiredPresence,
                &loaded)
            && AdoptLoadedSettings(loaded)) {
            __atomic_store_n(
                &g_journal_worker_state, 2, __ATOMIC_RELEASE);
            km::km_svc_exit_thread();
        }
        // Only authenticated journal readiness is retried. Every executable
        // hook was installed synchronously during subsdk startup and remains
        // immutable for the rest of the process lifetime.
        km_za_202_sleep_thread(1'000'000'000LL);
    }
}

void StartJournalRetryWorker() {
    if (IsJournalReady()) {
        return;
    }
    uint32_t idle = 0;
    if (!__atomic_compare_exchange_n(
            &g_journal_worker_state,
            &idle,
            1,
            false,
            __ATOMIC_ACQ_REL,
            __ATOMIC_ACQUIRE)) {
        return;
    }

    km::Handle thread = km::InvalidHandle;
    if (km::km_svc_create_thread(
            &thread,
            RetryJournal,
            nullptr,
            g_retry_stack + sizeof(g_retry_stack),
            0x2C,
            -2) != km::ResultSuccess) {
        // A later stock Game Settings callback retries this data-only worker
        // launch. Executable hooks remain immutable and retail-equivalent.
        __atomic_store_n(&g_journal_worker_state, 0, __ATOMIC_RELEASE);
        return;
    }
    if (km::km_svc_start_thread(thread) != km::ResultSuccess) {
        km::km_svc_close_handle(thread);
        __atomic_store_n(&g_journal_worker_state, 0, __ATOMIC_RELEASE);
        return;
    }
    // The kernel owns the running thread. Release only this userspace handle.
    km::km_svc_close_handle(thread);
}

uint32_t ReadCategory(const void* model) {
    return *reinterpret_cast<const uint32_t*>(
        reinterpret_cast<const uint8_t*>(model) + 0xB8);
}

void* ReadModel(void* page) {
    return *reinterpret_cast<void**>(
        reinterpret_cast<uint8_t*>(page) + 0x118);
}

KmZa202RowDescriptor ReadStockDescriptor(void* model, uint32_t row) {
    const auto category = ReadCategory(model);
    if (category >= 3 || row >= 3) {
        return {};
    }
    constexpr uintptr_t bases[] = {0x4C, 0x70, 0x94};
    KmZa202RowDescriptor output{};
    MemoryCopy(&output,
               reinterpret_cast<uint8_t*>(model) + bases[category] + row * 12,
               12);
    return output;
}

KmZa202RowDescriptor ReadCustomDescriptor(uint32_t row) {
    SettingsValues values{};
    if (!km::UnpackSettingsSnapshot(
            __atomic_load_n(&g_effective_snapshot, __ATOMIC_ACQUIRE),
            &values)) {
        return {};
    }
    switch (row) {
    case 3:
        return KmZa202RowDescriptor{1, 10,
            values.experience_share ? 0U : 1U, 0};
    case 4:
        return KmZa202RowDescriptor{2, 1,
            values.experience_rate_basis_points / 1000U, 0};
    case 5:
        return KmZa202RowDescriptor{2, 1,
            values.level_cap_enabled ? values.level_cap : 0U, 0};
    default:
        return {};
    }
}

void StoreDraft(const SettingsValues& values) {
    g_draft = values;
    g_dirty = !ValuesEqual(g_draft, g_persisted.values);
    __atomic_store_n(&g_effective_snapshot, PackValues(values), __ATOMIC_RELEASE);
}

void CommitOrRevertDraft() {
    if (!IsActive() || !IsJournalReady()) {
        return;
    }
    // Leaving the stock page is the durability boundary. Do not drop a commit
    // merely because the short journal-adoption path currently owns the lock.
    AcquireMenuLock();
    if (!IsActive() || !IsJournalReady()) {
        ReleaseMenuLock();
        return;
    }
    if (g_dirty) {
        SettingsState committed{};
        if (km::CommitSettingsJournal(
                g_filesystem,
                JournalPath,
                SettingsFamily::LegendsZA,
                TitleId,
                RequiredPresence,
                g_draft,
                &committed)) {
            g_persisted = committed;
            g_draft = committed.values;
            __atomic_store_n(&g_journal_ready, 1, __ATOMIC_RELEASE);
        } else {
            // A write can reach durable storage even if the subsequent
            // readback reports failure. Re-resolve both authenticated slots
            // before choosing the live value; never guess and diverge from
            // what the next launch will load.
            SettingsState reconciled{};
            if (km::LoadSettingsJournal(
                    g_filesystem,
                    JournalPath,
                    SettingsFamily::LegendsZA,
                    TitleId,
                    RequiredPresence,
                    &reconciled)) {
                g_persisted = reconciled;
                g_draft = reconciled.values;
                __atomic_store_n(&g_journal_ready, 1, __ATOMIC_RELEASE);
            } else {
                // The durable winner is unknowable. Disable the custom runtime
                // for this process so no further writes or policy decisions can
                // compound an indeterminate journal state. The next cold launch
                // resolves the authenticated slots before publishing settings.
                g_dirty = false;
                __atomic_store_n(&g_effective_snapshot, 0, __ATOMIC_RELEASE);
                __atomic_store_n(
                    &g_activation_state, ActivationRejected, __ATOMIC_RELEASE);
                ReleaseMenuLock();
                return;
            }
            __atomic_store_n(
                &g_effective_snapshot,
                PackValues(g_draft),
                __ATOMIC_RELEASE);
        }
        g_dirty = false;
    }
    ReleaseMenuLock();
}

uint64_t PackRowKindAndFlags(const KmZa202RowDescriptor& descriptor) {
    return static_cast<uint64_t>(descriptor.kind)
        | (static_cast<uint64_t>(descriptor.flags) << 32);
}

constexpr uint32_t CustomSliderVisualValue(
    uint32_t row, uint32_t logical_value) {
    if (row == 4) {
        const auto bounded = logical_value > 50 ? 50U : logical_value;
        return (bounded + 2U) / 5U;
    }
    if (row == 5) {
        const auto bounded = logical_value > 100 ? 100U : logical_value;
        return (bounded + 9U) / 10U;
    }
    return 0;
}
static_assert(CustomSliderVisualValue(4, 0) == 0);
static_assert(CustomSliderVisualValue(4, 50) == 10);
static_assert(CustomSliderVisualValue(4, 51) == 10);
static_assert(CustomSliderVisualValue(5, 0) == 0);
static_assert(CustomSliderVisualValue(5, 100) == 10);
static_assert(CustomSliderVisualValue(5, 101) == 10);

void RefreshRow(void* page, uint32_t row,
                const KmZa202RowDescriptor& descriptor,
                uint32_t value, bool increasing) {
    using Refresh = void (*)(void*, uint32_t, uint64_t, uint32_t, uint32_t);
    MainFunction<Refresh>(RefreshRowOffset)(
        page, row, PackRowKindAndFlags(descriptor), value,
        increasing ? 1U : 0U);
}

bool StepCustomRow(void* page, uint32_t row, bool increasing) {
    if (!IsJournalReady()) {
        StartJournalRetryWorker();
        return false;
    }
    // Journal adoption publishes readiness before it releases the menu lock.
    // Wait through that bounded overlap so a controller input is never lost.
    AcquireMenuLock();
    if (!IsJournalReady()) {
        ReleaseMenuLock();
        return false;
    }
    auto next = g_draft;
    uint32_t current = 0;
    uint32_t maximum = 0;
    if (row == 4) {
        current = next.experience_rate_basis_points / 1000U;
        maximum = 50;
    } else if (row == 5) {
        current = next.level_cap_enabled ? next.level_cap : 0U;
        maximum = 100;
    } else {
        ReleaseMenuLock();
        return false;
    }
    if ((increasing && current >= maximum)
        || (!increasing && current == 0)) {
        ReleaseMenuLock();
        return false;
    }
    const auto value = increasing ? current + 1U : current - 1U;
    if (row == 4) {
        next.experience_rate_basis_points = value * 1000U;
    } else if (value == 0) {
        next.level_cap_enabled = false;
        next.level_cap = 100;
    } else {
        next.level_cap_enabled = true;
        next.level_cap = static_cast<uint8_t>(value);
    }
    StoreDraft(next);
    ReleaseMenuLock();
    const auto descriptor = ReadCustomDescriptor(row);
    // The retail refresh helper owns a 0..10 animation domain. Keep KM's
    // logical 0..50 and 0..100 values in the journal and descriptor, but pass
    // only their stock-width visual projection to the animation path.
    RefreshRow(
        page, row, descriptor, CustomSliderVisualValue(row, value), increasing);
    return true;
}

} // namespace

extern "C" bool km_try_activate_za_202(
    const km::ModuleRange* modules,
    size_t module_count,
    const km::GuestFilesystemApi* filesystem) {
    if (modules == nullptr || filesystem == nullptr
        || filesystem->mount_sd == nullptr || filesystem->open_file == nullptr
        || filesystem->read_file == nullptr || filesystem->write_file == nullptr
        || filesystem->get_file_size == nullptr || filesystem->flush_file == nullptr
        || filesystem->close_file == nullptr) {
        return false;
    }

    uint64_t program_id = 0;
    if (km::km_svc_get_info(
            &program_id,
            ProgramIdInfoType,
            km::CurrentProcessPseudoHandle,
            0) != km::ResultSuccess
        || program_id != TitleId) {
        return false;
    }
    const auto state = __atomic_load_n(&g_activation_state, __ATOMIC_ACQUIRE);
    if (state == ActivationActive || state == ActivationRetrying) {
        return true;
    }
    if (state == ActivationRejected) {
        return false;
    }
    const auto* exact = FindExactMain(modules, module_count);
    if (exact == nullptr) {
        return false;
    }
    uint32_t idle = ActivationIdle;
    if (!__atomic_compare_exchange_n(
            &g_activation_state,
            &idle,
            ActivationRetrying,
            false,
            __ATOMIC_ACQ_REL,
            __ATOMIC_ACQUIRE)) {
        return idle == ActivationActive || idle == ActivationRetrying;
    }

    g_main = *exact;
    g_filesystem = *filesystem;
    km_za_202_main_base = exact->base;
    if (!PrepareValueMessageKeys()) {
        __atomic_store_n(
            &g_activation_state, ActivationRejected, __ATOMIC_RELEASE);
        return false;
    }

    SettingsState loaded{};
    const auto journal_ready = km::LoadSettingsJournal(
            g_filesystem,
            JournalPath,
            SettingsFamily::LegendsZA,
            TitleId,
            RequiredPresence,
            &loaded);
    if (!journal_ready) {
        loaded = SettingsState{
            SettingsFamily::LegendsZA,
            TitleId,
            0,
            RequiredPresence,
            km::VanillaSettings,
            0,
            false,
        };
    }

    // This call runs directly from the subsdk module entry while the loader is
    // still starting the process. Install the complete immutable hook set now,
    // with a fail-safe vanilla snapshot when SD is not ready. No later journal
    // or menu operation is permitted to modify executable memory.
    if (!InstallRuntime(loaded, journal_ready)) {
        __atomic_store_n(
            &g_activation_state, ActivationRejected, __ATOMIC_RELEASE);
        return false;
    }
    if (journal_ready) {
        return true;
    }
    StartJournalRetryWorker();
    return true;
}

extern "C" uint32_t km_za_202_row_count(void* model) {
    if (model == nullptr) {
        return 0;
    }
    const auto category = ReadCategory(model);
    if (category >= 3) {
        return 0;
    }
    const auto active = IsActive();
    if (active && category == 2 && !IsJournalReady()) {
        // If the loader-time worker launch failed transiently, opening this
        // stock page safely retries only authenticated data adoption.
        StartJournalRetryWorker();
    }
    return active && category == 2 ? 6 : 3;
}

extern "C" KmZa202RowDescriptor km_za_202_get_row(
    void* page, uint32_t row) {
    if (page == nullptr) {
        return {};
    }
    auto* model = ReadModel(page);
    if (model == nullptr) {
        return {};
    }
    const auto category = ReadCategory(model);
    if (IsActive() && category == 2 && row >= 3 && row < 6) {
        return ReadCustomDescriptor(row);
    }
    return ReadStockDescriptor(model, row);
}

extern "C" bool km_za_202_step_right(void* page) {
    if (page == nullptr) {
        return false;
    }
    auto* model = ReadModel(page);
    if (model == nullptr) {
        return false;
    }
    const auto row = *reinterpret_cast<const uint32_t*>(
        reinterpret_cast<const uint8_t*>(model) + 0xBC);
    if (IsActive() && ReadCategory(model) == 2 && (row == 4 || row == 5)) {
        return StepCustomRow(page, row, true);
    }
    const auto descriptor = km_za_202_get_row(page, row);
    if (descriptor.kind != 2) {
        return false;
    }
    const auto maximum = descriptor.flags == 0 ? 5U : 10U;
    if (descriptor.value >= maximum) {
        return false;
    }
    const auto value = descriptor.value + 1U;
    km_za_202_apply_row(page, row, value);
    RefreshRow(page, row, descriptor, value, true);
    return true;
}

extern "C" bool km_za_202_step_left(void* page) {
    if (page == nullptr) {
        return false;
    }
    auto* model = ReadModel(page);
    if (model == nullptr) {
        return false;
    }
    const auto row = *reinterpret_cast<const uint32_t*>(
        reinterpret_cast<const uint8_t*>(model) + 0xBC);
    if (IsActive() && ReadCategory(model) == 2 && (row == 4 || row == 5)) {
        return StepCustomRow(page, row, false);
    }
    const auto descriptor = km_za_202_get_row(page, row);
    if (descriptor.kind != 2) {
        return false;
    }
    const auto minimum = descriptor.flags == 0 ? 1U : 0U;
    if (descriptor.value <= minimum) {
        return false;
    }
    const auto value = descriptor.value - 1U;
    km_za_202_apply_row(page, row, value);
    RefreshRow(page, row, descriptor, value, false);
    return true;
}

extern "C" void km_za_202_apply_row(
    void* page, uint32_t row, uint32_t value) {
    if (page == nullptr) {
        return;
    }
    auto* model = ReadModel(page);
    if (model == nullptr) {
        return;
    }
    const auto category = ReadCategory(model);
    if (IsActive() && category == 2 && row >= 3 && row < 6) {
        if (!IsJournalReady()) {
            StartJournalRetryWorker();
            return;
        }
        AcquireMenuLock();
        if (!IsJournalReady()) {
            ReleaseMenuLock();
            return;
        }
        auto next = g_draft;
        auto valid = true;
        switch (row) {
        case 3:
            if (value > 1) {
                valid = false;
            } else {
                next.experience_share = value == 0;
            }
            break;
        case 4:
            if (value > 50) {
                valid = false;
            } else {
                next.experience_rate_basis_points = value * 1000U;
            }
            break;
        case 5:
            if (value > 100) {
                valid = false;
            } else if (value == 0) {
                next.level_cap_enabled = false;
                next.level_cap = 100;
            } else {
                next.level_cap_enabled = true;
                next.level_cap = static_cast<uint8_t>(value);
            }
            break;
        default:
            valid = false;
            break;
        }
        if (valid) {
            StoreDraft(next);
        }
        ReleaseMenuLock();
        return;
    }

    using Apply = void (*)(void*, uint32_t, uint32_t);
    switch (category) {
    case 0:
        MainFunction<Apply>(ApplyCategory0Offset)(model, row, value);
        break;
    case 1:
        MainFunction<Apply>(ApplyCategory1Offset)(model, row, value);
        break;
    case 2:
        MainFunction<Apply>(ApplyCategory2Offset)(model, row, value);
        break;
    default:
        break;
    }
}

extern "C" void km_za_202_render_row(
    void* text_view,
    void* row_handle,
    uint32_t category,
    uint32_t row,
    uint32_t value) {
    if (text_view == nullptr || row_handle == nullptr) {
        return;
    }
    using StockRender = void (*)(void*, void*, uint32_t, uint32_t);
    using SetTitle = void (*)(void*, void*, const MessageKey*);
    using SetToggle = void (*)(void*, void*, const MessageKey*, const MessageKey*);
    using SetSlider = void (*)(void*, void*, uint32_t);
    if (IsActive() && category == 2 && row >= 3 && row < 6) {
        const MessageKey* title = &ExperienceShareNameKey;
        if (row == 4 && value <= 50) {
            title = &g_experience_rate_value_keys[value];
        } else if (row == 4) {
            title = &ExperienceRateNameKey;
        } else if (row == 5 && value == 0) {
            title = &LevelCapOffKey;
        } else if (row == 5 && value <= 100) {
            title = &g_level_cap_value_keys[value - 1];
        } else if (row == 5) {
            title = &LevelCapNameKey;
        }
        MainFunction<SetTitle>(SetRowTitleOffset)(text_view, row_handle, title);
        if (row == 3) {
            MainFunction<SetToggle>(SetToggleLabelsOffset)(
                text_view, row_handle, &EnabledKey, &DisabledKey);
        } else {
            MainFunction<SetSlider>(SetSliderValueOffset)(
                text_view, row_handle, CustomSliderVisualValue(row, value));
        }
        return;
    }
    switch (category) {
    case 0:
        MainFunction<StockRender>(RenderCategory0Offset)(
            text_view, row_handle, row, value);
        break;
    case 1:
        MainFunction<StockRender>(RenderCategory1Offset)(
            text_view, row_handle, row, value);
        break;
    case 2:
        MainFunction<StockRender>(RenderCategory2Offset)(
            text_view, row_handle, row, value);
        break;
    default:
        break;
    }
}

extern "C" void km_za_202_render_description(
    void* text_view, uint32_t category, uint32_t row) {
    if (text_view == nullptr) {
        return;
    }
    using StockDescribe = void (*)(void*, uint32_t);
    using SetDescription = void (*)(void*, const MessageKey*);
    if (IsActive() && category == 2 && row >= 3 && row < 6) {
        const MessageKey* description = row == 3 ? &ExperienceShareDescriptionKey
            : row == 4 ? &ExperienceRateDescriptionKey : &LevelCapDescriptionKey;
        MainFunction<SetDescription>(SetDescriptionOffset)(text_view, description);
        return;
    }
    switch (category) {
    case 0:
        MainFunction<StockDescribe>(DescribeCategory0Offset)(text_view, row);
        break;
    case 1:
        MainFunction<StockDescribe>(DescribeCategory1Offset)(text_view, row);
        break;
    case 2:
        MainFunction<StockDescribe>(DescribeCategory2Offset)(text_view, row);
        break;
    default:
        break;
    }
}

extern "C" void km_za_202_reset(void* model) {
    if (model == nullptr) {
        return;
    }
    if (IsActive() && !IsJournalReady()) {
        StartJournalRetryWorker();
    } else if (IsActive()) {
        // Reset is a user mutation just like stepping or toggling a row. Wait
        // through journal adoption rather than silently dropping the reset.
        AcquireMenuLock();
        if (IsActive() && IsJournalReady()) {
            StoreDraft(km::VanillaSettings);
        }
        ReleaseMenuLock();
    }

    // Preserve the exact stock reset synchronization and settings reset.
    const auto barrier_owner = *reinterpret_cast<uintptr_t*>(
        km_za_202_main_base + StockRuntimeBarrierPointerOffset);
    if (barrier_owner != 0) {
        (void)*reinterpret_cast<volatile uint32_t*>(barrier_owner + 0x140);
        asm volatile("dmb ishld" ::: "memory");
    }
    using GetContext = void* (*)();
    using ResetContext = void (*)(void*);
    using ResetModel = void (*)(void*);
    auto* context = MainFunction<GetContext>(GetRuntimeContextOffset)();
    if (context != nullptr) {
        MainFunction<ResetContext>(ResetRuntimeContextOffset)(context);
    }
    MainFunction<ResetModel>(ResetModelOffset)(model);
}

extern "C" void km_za_202_back(void* callback) {
    CommitOrRevertDraft();
    km_za_202_back_original(callback);
}

extern "C" uint32_t km_za_202_share_callback(
    float scalar, void* first, void* second, uint32_t eligible) {
    using AwardBuilder = uint32_t (*)(float, void*, void*, uint32_t);
    const auto retail = MainFunction<AwardBuilder>(AwardBuilderOffset)(
        scalar, first, second, eligible);
    if (!IsActive()) {
        return retail;
    }
    SettingsValues values{};
    if (!km::UnpackSettingsSnapshot(
            __atomic_load_n(&g_effective_snapshot, __ATOMIC_ACQUIRE),
            &values)) {
        return retail;
    }
    return !values.experience_share && eligible == 0 ? 0 : retail;
}

extern "C" void km_za_202_rate_callback(
    void* recipient, void* result, uint32_t award) {
    if (result == nullptr) {
        return;
    }
    auto* accumulator = reinterpret_cast<uint32_t*>(
        reinterpret_cast<uint8_t*>(result) + 0x18);
    SettingsValues values{};
    if (!IsActive() || !km::UnpackSettingsSnapshot(
            __atomic_load_n(&g_effective_snapshot, __ATOMIC_ACQUIRE),
            &values)) {
        // Replay the displaced retail ADD W8, W8, W23 exactly. In particular,
        // the 32-bit instruction wraps rather than saturating on an artificial
        // overflow fixture.
        *accumulator += award;
        return;
    }
    if (values.experience_rate_basis_points == 10000
        && (!values.level_cap_enabled || values.level_cap == 100)) {
        // The default rate and a disabled/effectively-unbounded cap must remain
        // byte-for-byte equivalent to the displaced retail arithmetic.
        *accumulator += award;
        return;
    }

    const auto product = static_cast<uint64_t>(award)
        * values.experience_rate_basis_points;
    auto scaled = product / 10000U;
    if (award != 0 && values.experience_rate_basis_points != 0 && scaled == 0) {
        scaled = 1;
    }
    if (scaled > UINT32_MAX) {
        scaled = UINT32_MAX;
    }
    auto total = static_cast<uint64_t>(*accumulator) + scaled;
    if (total > UINT32_MAX) {
        total = UINT32_MAX;
    }

    // Level 100 is the retail maximum, so an enabled cap of 100 is
    // semantically uncapped and must never query a nonexistent level 101.
    if (values.level_cap_enabled && values.level_cap < 100
        && recipient != nullptr) {
        auto* creature = *reinterpret_cast<void**>(
            reinterpret_cast<uint8_t*>(recipient) + 0x70);
        if (creature != nullptr) {
            using GetValue = uint32_t (*)(void*);
            using GetMinimum = uint32_t (*)(uint32_t, uint32_t, uint32_t);
            const auto species = MainFunction<GetValue>(SpeciesGetterOffset)(creature);
            const auto form = MainFunction<GetValue>(FormGetterOffset)(creature);
            const auto at_next_level = MainFunction<GetMinimum>(
                MinimumTotalExperienceOffset)(species, form, values.level_cap + 1U);
            const auto maximum = at_next_level == 0 ? 0 : at_next_level - 1U;
            const auto current = MainFunction<GetValue>(
                CurrentTotalExperienceOffset)(creature);
            const auto remaining = current >= maximum ? 0U : maximum - current;
            if (total > remaining) {
                total = remaining;
            }
        }
    }
    *accumulator = static_cast<uint32_t>(total);
}
