/* SPDX-License-Identifier: GPL-3.0-only */

export const workbenchSections = [
  'health',
  'workbench',
  'workflows',
  'items',
  'pokemon',
  'dexLayout',
  'moves',
  'text',
  'trainers',
  'giftPokemon',
  'tradePokemon',
  'staticEncounters',
  'rentalPokemon',
  'dynamaxAdventures',
  'shops',
  'encounters',
  'teraRaids',
  'raidBattles',
  'raidRewards',
  'raidBonusRewards',
  'placement',
  'behavior',
  'flagworkSave',
  'bagHook',
  'catchCap',
  'hyperTraining',
  'shinyRate',
  'typeChart',
  'angeFight',
  'fairyGymBoosts',
  'fashionUnlock',
  'gymUniformRemoval',
  'hyperspaceBypass',
  'ivScreen',
  'exefsPatches',
  'royalCandy',
  'startingItems',
  'npcItemGift',
  'spreadsheetImport',
  'modMerger',
  'fpsPatch',
  'profanityFilter',
  'randomizer',
  'gameDump',
  'changes',
  'settings'
] as const;

export type WorkbenchSection = (typeof workbenchSections)[number];
